### ISSUE TITLE
generate docs for client-side method names

### ISSUE THREAD

**Issue by enricop** [Dorin-Mocan/SignalRSwaggerGen#15]
Hello,
thank you for this gread tool that helps documenting SignalR services for frontend developers.

It would be great to expose in the generated documentation also Hub's "event" names as OpenAPI "callbacks".
https://swagger.io/docs/specification/callbacks/

Is documenting "client methods" names already supported?
I'm referring to the names passed as argument to
`await Clients.All.SendAsync("clientMethodName", TestArgument.TestErrorStatus);`

thanks

**Comment by Dorin-Mocan** [comment]
@enricop , there's no support for callbacks currently. I could add, but you'll have to wait some time, because I'm running a company now and am pretty busy. Regarding client methods, you can have strongly typed hubs like below:

```
[SignalRHub]
public class StronglyTypedHub : Hub<IStronglyTypedHub>
{
	public async Task ServerMethod()
	{
		await Clients.All.ClientMethod(1, "something");
	}
}

[SignalRHub]
public interface IStronglyTypedHub
{
	public ValueTask ClientMethod(int agr1, string arg2);
}
```

This should be enough to cover your need to display client methods on swagger doc. If for some reason it does not work for you or something not clear, let me know and I'll try to help.
