### ISSUE TITLE
missing / after base url causing 404

### ISSUE THREAD

**Issue by imabusyman** [Dorin-Mocan/SignalRSwaggerGen#22]
https://localhost:44392hubs/StronglyTypedTestHub/TestMethod

This is even on your test samples, but the above URL is missing / before hubs

**Comment by imabusyman** [comment]
i fixed it by adding SignalRHub.Path property to "/hubs" or whatever I name it, but if that isn't there, it errors.

**Comment by Dorin-Mocan** [comment]
@imabusyman , thanks for raising this issue. Indeed it's a bug from my side. I need to prepend a slash. I'll release a new version soon. Good that you found a solution, however there's a better option. Instead of setting a hub path for each hub, you can just set a function that will calculate the hub path. It can be done in the extension method AddSignalRSwaggerGen(options=>{...});

**Comment by Dorin-Mocan** [comment]
I released the version 3.2.1 containing a fix for this issue.
