### ISSUE TITLE
swashbuckle CLI integration

### ISSUE THREAD

**Issue by jeremyh3** [Dorin-Mocan/SignalRSwaggerGen#25]
The tool works great in a standalone development project.  However, when we build our project, we use the swashbuckle CLI tool to pre-generate the swagger pages (to make them faster to load), its not running the component.   
We the following steps to pre build the project and swagger output:
dotnet restore
dotnet build
dotnet tool restore --tool-manifest <path-to-config>/dotnet-tools.json
dotnet swagger tofile --output <output-path>/swagger.json <path-to-dotnet-dll> <version>

The last two commands are what generated the swagger.json file for our project (the dotnet-tools.json contains a reference to swashbuckle.aspnetcore.cli" v 6.3.0).   So its not including your signalr generation component in the generation.  Any idea on how to make the "AddSignalRSwaggerGen" component part of that swagger/swashbuckle CLI execution?

**Comment by Dorin-Mocan** [comment]
@jeremyh3 , I'll investigate and come back to you as soon as I have an answer. Stay tuned. Thank you!

**Comment by Dorin-Mocan** [comment]
@jeremyh3 , I think the problem is that you need to explicitly specify what assemblies to be scanned by SignalRSwaggerGen, because by default it scans the entry assembly, and in your case it will be the assembly of the swagger cli, which of course does not have any hubs. You can specify the assemblies in AddSignalRSwaggerGen(opt => opt.ScanAssembly(...)). Please try this and if doesn't fix your problem, I have one more idea up my sleeve.

**Comment by jeremyh3** [comment]
Thanks for the response.  You suggestion seems to be correct and did solve the problem!  Added the following in my Startup.ConfigureServices method:

c.AddSignalRSwaggerGen(opts =>
{
	Assembly asm = Assembly.GetAssembly(typeof(Program));
	opts.ScanAssembly(asm);                            // use Program assembly if running under swagger CLI tool
});

Thank you!
